import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    logo: {
      width: 500,
      height: 200,
      marginBottom: 30,
    },
    formTitle: {
      fontSize: 25,
      fontWeight: 'bold',
      color: 'green',
      margin: 5,
    },
    formTitle2: {
      fontSize: 30,
      fontWeight: 'bold',
      color: 'black',
      margin: 20,
    },
    formInput: {
      borderColor: 'black',
      borderWidth: 1,
      borderRadius:10,
      fontSize: 22,
      width:'80%',
      padding: 10,
      margin: 10,
    },
    formButton: {
      backgroundColor: 'blue',
      width: '80%',
      margin: 15,
      padding: 20,
      borderRadius: 10,
      alignItems: 'center',

    },
    textButton: {
      color: 'white',
      fontSize: 20,
      fontWeight: 'bold',
    },
    subContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '80%',
    },
    subButton: {
      padding: 10,
      alignItems: 'center',
    },
    subTextButton: {
      color: 'black',
    },
    formBarTitle2: {
      fontSize: 38,
      fontWeight: 'bold',
      color: 'black',
      margin: 10,
    },
    internalContainer: {
      flex: 1,
      alignItems: 'center',
      paddingTop: 50,
      backgroundColor: '#fff',
      justifyContent: 'flex-start',
    },
    topBar: {
      flexDirection: 'row-reverse',
      padding: 10,
      backgroundColor: 'silver',
      width: '100%',
    },
    topBarButtonText: {
      color: 'black',
      fontSize: 20,
      fontWeight: '700',
    },
    topBarButtonText1: {
      color: 'black',
      fontSize: 30,
      fontWeight: '700',
    },
    formBarTitle: {
      fontSize: 38,
      fontWeight: 'bold',
      color: 'black',
      margin: 10,
    },
    container2: {
      flex: 1,
      padding: 20,
    },
    backButton: {
      backgroundColor: 'blueviolet',
      padding: 10,
      alignItems: 'center',
      borderRadius: 10,
      marginBottom: 20,
      width: '20%',
    },
    formTitle: {
      fontSize: 30,
      fontWeight: 'bold',
      color: 'black',
      margin: 10,
    },
    backButtonText: {
      color: 'white',
      fontSize: 25,
      fontWeight: 'bold',
    },
    item: {
      marginBottom: 20,
      padding: 10,
      borderColor: 'blueviolet',
      borderWidth: 1,
      borderRadius: 5,
    },
    button: {
      backgroundColor: 'red',
      padding: 10,
      alignItems: 'center',
      borderRadius: 10,
      marginTop: 10,
    },
    button2: {
      backgroundColor: 'green',
      padding: 10,
      alignItems: 'center',
      borderRadius: 5,
      marginTop: 10,
    },
    button3: {
      backgroundColor: 'blue',
      padding: 10,
      alignItems: 'center',
      borderRadius: 5,
      marginTop: 10,
    },
    buttonText: {
      color: 'white',
      fontSize: 25,
      fontWeight: 'bold',
    },
    container3: {
      flex: 1,
      padding: 20,
    },
    backButton: {
      backgroundColor: 'blueviolet',
      padding: 10,
      alignItems: 'center',
      borderRadius: 10,
      marginBottom: 20,
      width: '20%',
    },
    formTitle: {
      fontSize: 25,
      fontWeight: 'bold',
      color: 'black',
      margin: 10,
    },
    backButtonText: {
      color: 'white',
      fontSize: 25,
      fontWeight: 'bold',
    },
    item: {
      marginBottom: 20,
      padding: 10,
      borderColor: 'blueviolet',
      borderWidth: 1,
      borderRadius: 10,
    },
    editContainer: {
      marginTop: 20,
    },
     button: {
      backgroundColor: 'orange',
      padding: 10,
      alignItems: 'center',
      borderRadius: 5,
      marginTop: 10,
    },
    buttonText: {
      color: 'white',
      fontSize: 25,
      fontWeight: 'bold',
    },
    container4: {
      flex: 1,
      padding: 20,
    },
    backButton: {
      backgroundColor: 'blueviolet',
      padding: 10,
      alignItems: 'center',
      borderRadius: 10,
      marginBottom: 20,
      width: '20%',
    },
    formTitle: {
      fontSize: 25,
      fontWeight: 'bold',
      color: 'black',
      margin: 10,
    },
    backButtonText: {
      color: 'white',
      fontSize: 25,
      fontWeight: 'bold',
    },
    item: {
      marginBottom: 20,
      padding: 10,
      borderColor: 'black',
      borderWidth: 1,
      borderRadius: 10,
    },
    button: {
      backgroundColor: 'red',
      padding: 10,
      alignItems: 'center',
      borderRadius: 5,
      marginTop: 10,
    },
    buttonText: {
      color: 'white',
      fontSize: 25,
      fontWeight: 'bold',
    },
    container5: {
      flex: 1,
      padding: 20,
    },
    item2: {
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#ccc',
    },
    editContainer: {
      marginTop: 20,
    },
    formButton2: {
      backgroundColor: 'green',
      padding: 10,
      alignItems: 'center',
      borderRadius: 5,
      marginTop: 10,
    },
    textButton: {
      color: 'white',
      fontSize: 25,
      fontWeight: 'bold',
    },
});